import { beforeEach, afterEach, expect, it, vi } from 'vitest';
import { defaultRules, ruleMinutes, matchWinner, resultReason, disqualificationLimit, grapplingActions, type Rules } from './rules';
import { useMatchStore } from '../stores/matchStore';
const get=()=>useMatchStore.getState();
const uww:Rules={sport:'grappling',category:'senior',belt:'white',actions:grapplingActions};
it('disqualification takes priority over points and overtime defence',()=>{get().setup('A','B',1000,uww);get().score('A','points',20);for(let i=0;i<4;i++)get().score('A','penalties',1);expect(matchWinner(get().match)).toBe('B');expect(resultReason(get().match,'B')).toBe('disqualification');});
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(1000);get().reset();});
afterEach(()=>vi.useRealTimers());
it.each([['kids4','white',2],['kids7','white',3],['kids10','white',4],['kids13','white',4],['juvenile','purple',5],['adult','black',10],['adult','blue',6],['master1','black',6],['master1','blue',5],['master2','black',5]])('IBJJF %s %s duration', (category,belt,minutes)=>expect(ruleMinutes({...defaultRules(),category:category as string,belt:belt as string})).toBe(minutes));
it('UWW durations and age-specific DQ limits',()=>{expect(ruleMinutes({...uww,category:'u17'})).toBe(5);expect(ruleMinutes({...uww,category:'u15'})).toBe(4);expect(disqualificationLimit({...defaultRules(),category:'kids13'})).toBe(6);expect(disqualificationLimit(defaultRules())).toBe(4);});
it('IBJJF penalty awards undo and redo atomically without touching clock',()=>{get().setup('A','B',300000);get().toggleTimer();const end=get().match.endTimestamp;get().score('A','penalties',1);get().score('A','penalties',1);expect(get().match.competitorB.advantages).toBe(1);get().score('A','penalties',1);expect(get().match.competitorB.points).toBe(2);get().undo();expect(get().match.competitorA.penalties).toBe(2);expect(get().match.competitorB.points).toBe(0);get().redo();expect(get().match.competitorB.points).toBe(2);expect(get().match.endTimestamp).toBe(end);get().score('A','penalties',-1);expect(get().match.competitorB.points).toBe(0);});
it('children receive extra penalty awards on fourth and fifth cautions',()=>{get().setup('A','B',240000,{...defaultRules(),category:'kids13'});for(let i=0;i<5;i++)get().score('A','penalties',1);expect(get().match.competitorB.points).toBe(6);expect(get().match.competitorB.advantages).toBe(1);});
it('UWW uses high-value action counts before cautions, and undo removes those actions',()=>{get().setup('A','B',300000,uww);get().score('A','points',4);get().score('B','points',2);get().score('B','points',2);expect(matchWinner(get().match)).toBe('A');get().undo();expect(matchWinner(get().match)).toBe('A');get().score('B','points',2);get().score('A','penalties',1);get().score('B','penalties',1);expect(get().match.competitorA.points).toBe(5);expect(matchWinner(get().match)).toBe('A');get().score('A','advantages',1);expect(get().match.competitorA.advantages).toBe(0);});
it('UWW tied regulation permits one-minute overtime, no technical points, defender wins at expiry',()=>{get().setup('A','B',1000,uww);get().toggleTimer();vi.advanceTimersByTime(1000);get().tick();expect(get().match.winner).toBeNull();get().startOvertime('B');get().score('B','points',4);get().score('A','penalties',1);expect(get().match.competitorB.points).toBe(0);expect(get().match.competitorA.penalties).toBe(1);get().toggleTimer();vi.advanceTimersByTime(60000);get().tick();expect(get().match.winner).toBe('A');});
it('custom actions and colors survive persistence; winner presentation synchronizes as match state',()=>{get().setup('A','B',300000,{sport:'custom',category:'custom',belt:'white',actions:[{label:'Action',points:7}]},['red','blue']);get().score('A','points',7);get().finish('A','decision');get().replace(JSON.parse(JSON.stringify(get().match)));expect(get().match.competitorA.color).toBe('red');expect(get().match.rules.actions[0].points).toBe(7);expect(get().match.showWinner).toBe(true);get().presentWinner(false);expect(get().match.confirmed).toBe(true);});
it('old saved matches get safe rules and color defaults',()=>{get().setup('A','B',300000);const legacy=JSON.parse(JSON.stringify(get().match));delete legacy.rules;delete legacy.showWinner;delete legacy.competitorA.color;get().replace(legacy);expect(get().match.rules.sport).toBe('bjj');expect(get().match.competitorA.color).toBe('red');expect(get().match.competitorB.color).toBe('blue');expect(get().match.showWinner).toBe(false);});

it('defaults to BJJ, configures rules in setup, and locks them after timer start',()=>{expect(get().match.rules.sport).toBe('bjj');get().configureRules(uww);expect(get().match.rules.sport).toBe('grappling');get().setup('A','B',300000,uww);get().toggleTimer();get().configureRules(defaultRules());expect(get().match.rules.sport).toBe('grappling');get().reset();expect(get().match.rules.sport).toBe('bjj');});
