import {test,expect} from '@playwright/test';
test('centered setup, age durations, red/blue colors, UWW points and animated winner sync',async({page,context})=>{
  await page.goto('/');
  await expect(page.getByRole('checkbox')).toHaveCount(0);
  await page.getByLabel('Настройки',{exact:true}).click();
  await page.getByLabel('Возрастная категория').selectOption('kids4');
  await expect(page.getByLabel('Длительность схватки')).toHaveValue('02:00');
  await page.getByLabel('Возрастная категория').selectOption('master1');
  await page.getByLabel('Пояс',{exact:true}).selectOption('black');
  await expect(page.getByLabel('Длительность схватки')).toHaveValue('06:00');
  await page.getByLabel('Греплинг · UWW',{exact:true}).check();
  await page.getByLabel('Возрастная категория').selectOption('u17');
  await expect(page.getByLabel('Длительность схватки')).toHaveValue('05:00');
  await page.getByLabel('Закрыть диалог').click();
  await page.getByLabel('Спортсмен A',{exact:true}).fill('Александр Иванов');
  await page.getByLabel('Спортсмен B',{exact:true}).fill('Максим Петров');
  await page.getByLabel('Цвет спортсмена A').selectOption('red');
  await page.getByLabel('Цвет спортсмена B').selectOption('blue');
  await page.screenshot({path:'test-results/setup-new.png'});
  const box=await page.locator('.setup-card').boundingBox();
  expect(Math.abs(box!.x+box!.width/2-683)).toBeLessThan(2);
  await page.getByRole('button',{name:'СОЗДАТЬ СХВАТКУ'}).click();
  const popup=context.waitForEvent('page');await page.getByRole('button',{name:'Открыть зрительское табло'}).click();const display=await popup;
  await expect(display.locator('.competitor.red')).toContainText('Александр Иванов');
  await expect(page.getByTestId('advantages-A')).toHaveCount(0);
  await page.getByLabel('A: плюс 1',{exact:true}).click();
  await page.getByLabel('B: Штраф, увеличить',{exact:true}).click();
  await expect(display.getByTestId('score-A')).toHaveText('2');
  await page.getByRole('button',{name:'Отменить',exact:false}).click();
  await expect(display.getByTestId('score-A')).toHaveText('1');
  await expect(display.getByTestId('penalties-B')).toHaveText('0');
  await page.getByRole('button',{name:'Действия и баллы'}).first().click();
  await page.getByRole('button',{name:'Амплитудный перевод'}).click();
  await expect(display.getByTestId('score-A')).toHaveText('4');
  await page.getByRole('button',{name:'Сабмишн',exact:true}).click();
  await page.getByRole('button',{name:'КРАСНЫЙ Александр Иванов'}).click();
  await page.getByRole('button',{name:'Подтвердить победу',exact:true}).click();
  const winner=display.getByRole('dialog',{name:'Победитель'});
  await expect(winner.getByRole('heading')).toHaveText('Александр Иванов');
  await expect(winner).toHaveClass(/red/);
  await display.screenshot({path:'test-results/winner-new.png',animations:'disabled'});
  await page.getByRole('button',{name:'Вернуться к табло'}).click();
  await expect(winner).toHaveCount(0);
  await display.screenshot({path:'test-results/display-new.png'});
});
test('custom actions editor saves, validates, persists and awards configured points',async({page})=>{
  await page.goto('/');
  await expect(page.getByRole('checkbox')).toHaveCount(0);
  await page.getByLabel('Настройки',{exact:true}).click();
  await page.getByLabel('Добавить свои правила',{exact:true}).click();
  const modal=page.getByRole('dialog').filter({has:page.getByRole('heading',{name:'Свои правила начисления очков'})});
  await modal.getByLabel('Действие',{exact:true}).fill('Удержание');
  await modal.getByLabel('Баллы',{exact:true}).fill('7');
  await modal.getByRole('button',{name:'Добавить действие'}).click();
  await expect(modal.getByText('Удержание',{exact:true})).toBeVisible();
  await modal.getByLabel('Действие',{exact:true}).fill('Удержание');
  await expect(modal.getByRole('button',{name:'Добавить действие'})).toBeDisabled();
  await page.screenshot({path:'test-results/custom-editor.png'});
  await modal.getByRole('button',{name:'Сохранить правила'}).click();
  await page.getByLabel('Закрыть диалог').click();
  await page.getByLabel('Спортсмен A',{exact:true}).fill('Анна');await page.getByLabel('Спортсмен B',{exact:true}).fill('Мария');
  await page.getByRole('button',{name:'СОЗДАТЬ СХВАТКУ'}).click();
  await page.getByRole('button',{name:'Действия и баллы'}).first().click();
  await page.getByRole('button',{name:'Удержание'}).click();
  await expect(page.getByTestId('score-A')).toHaveText('7');
  await page.keyboard.press('q');await expect(page.getByTestId('score-A')).toHaveText('7');
  page.on('dialog',d=>d.accept());await page.reload();await page.getByRole('button',{name:'ВОССТАНОВИТЬ СХВАТКУ'}).click();
  await expect(page.getByTestId('score-A')).toHaveText('7');
  await page.getByLabel('Настройки',{exact:true}).click();
  await expect(page.getByLabel('Добавить свои правила',{exact:true})).toBeChecked();
});
