import { test, expect } from '@playwright/test';
test.beforeEach(async ({page}) => {
  await page.addInitScript(() => { if (!localStorage.getItem('tatami.settings.v1')) localStorage.setItem('tatami.settings.v1',JSON.stringify({locale:'en',startSound:true,endSound:true})); });
});
test('operator scenario, display sync, recovery and time expiry', async ({ page, context }) => {
  await page.goto('/');
  await page.getByLabel('Competitor A', { exact:true }).fill('Ivan');
  await page.getByLabel('Competitor B', { exact:true }).fill('Petr');
  await page.getByRole('button', { name:'5m', exact:true }).click();
  await page.getByRole('button', { name:'START MATCH' }).click();
  const popup = context.waitForEvent('page');
  await page.getByRole('button', { name:'Open Scoreboard Display', exact:false }).click();
  const display = await popup;
  await expect(display.getByRole('heading', { name:'Ivan', exact:true })).toBeVisible();
  await expect(display.getByRole('button')).toHaveCount(0);
  await page.getByRole('button', { name:'START TIMER' }).click();
  await page.getByRole('button', { name:'A plus 2', exact:true }).click();
  await page.getByRole('button', { name:'B plus 4', exact:true }).click();
  await page.getByLabel('A advantages plus', { exact:true }).click();
  await page.getByLabel('B penalties plus', { exact:true }).click();
  await page.getByRole('button', { name:'Undo', exact:false }).click();
  await expect(page.getByTestId('penalties-B')).toHaveText('0');
  await page.getByRole('button', { name:'Redo', exact:false }).click();
  await expect(display.getByTestId('score-A')).toHaveText('2');
  await expect(display.getByTestId('score-B')).toHaveText('4');
  await expect(display.getByTestId('advantages-A')).toHaveText('1');
  await expect(display.getByTestId('penalties-B')).toHaveText('1');
  await page.getByRole('button', { name:'PAUSE', exact:false }).click();
  await page.getByLabel('Edit remaining time').click();
  await page.getByRole('textbox', {name:'Remaining time'}).fill('04:00');
  await page.getByRole('button', { name:'Confirm change' }).click();
  await expect(page.getByLabel('Edit remaining time')).toHaveText('04:00');
  await page.screenshot({ path:'test-results/control-1366.png' });
  await expect(page.locator('body')).toHaveJSProperty('scrollHeight',768);
  await page.getByRole('button', { name:'RESUME', exact:false }).click();
  page.on('dialog', dialog => dialog.accept());
  await page.reload();
  await page.getByRole('button', { name:'RESTORE PREVIOUS MATCH' }).click();
  await expect(page.getByTestId('score-A')).toHaveText('2');
  await expect(display.getByTestId('score-A')).toHaveText('2');
  await page.getByLabel('Edit remaining time').click();
  await page.getByRole('textbox', {name:'Remaining time'}).fill('00:01');
  await page.getByRole('button', { name:'Confirm change' }).click();
  await expect(display.getByText('TIME EXPIRED', { exact:true })).toBeVisible();
  await expect(display.getByText('Petr LEADS')).toBeVisible();
  const decision = page.getByRole('dialog');
  await expect(decision).toBeVisible();
  await expect(decision.locator('.winner-option[aria-pressed="true"]')).toHaveCount(1);
  await decision.getByRole('button', { name:'Confirm victory' }).click();
  await expect(display.getByRole('dialog',{name:'Winner'}).getByRole('heading',{name:'Petr'})).toBeVisible();
  await display.screenshot({ path:'test-results/display.png' });
  await page.setViewportSize({width:1920,height:1080});
  await page.screenshot({path:'test-results/control-1920.png'});
  await expect(page.locator('body')).toHaveJSProperty('scrollHeight',1080);
});
test('shortcuts ignore editing, dialogs and repeat; submission requires confirmation', async ({page}) => {
  await page.goto('/');
  await page.getByLabel('Competitor A', {exact:true}).fill('Ivan');
  await page.getByLabel('Competitor B', {exact:true}).fill('Petr');
  await page.getByRole('button',{name:'START MATCH'}).click();
  await page.keyboard.press('q'); await expect(page.getByTestId('score-A')).toHaveText('2');
  await page.keyboard.press('Control+z'); await expect(page.getByTestId('score-A')).toHaveText('0');
  await page.keyboard.press('Control+Shift+z'); await expect(page.getByTestId('score-A')).toHaveText('2');
  await page.dispatchEvent('body','keydown',{code:'KeyQ',key:'q',repeat:true});
  await expect(page.getByTestId('score-A')).toHaveText('2');
  await page.getByRole('button',{name:'Scoring actions',exact:false}).first().click();
  await page.keyboard.press('q');
  await expect(page.getByTestId('score-A')).toHaveText('2');
  await page.getByRole('button',{name:'Sweep'}).click();
  await expect(page.getByTestId('score-A')).toHaveText('4');
  await page.getByRole('button',{name:'EDIT',exact:true}).first().click();
  await page.getByLabel('Athlete name').fill('QWE');
  await page.keyboard.press('q');
  await page.getByRole('button',{name:'Confirm change'}).click();
  await expect(page.getByTestId('score-A')).toHaveText('4');
  await page.getByRole('button',{name:'Submission',exact:true}).click();
  await page.getByRole('button',{name:'BLUE Petr'}).click();
  await expect(page.getByText('Confirm submission victory for')).toBeVisible();
  await page.getByRole('button',{name:'Confirm victory'}).click();
  await expect(page.getByText('Petr WINS')).toBeVisible();
  await page.getByRole('button',{name:'Back to scoreboard'}).click();
  await page.getByRole('button',{name:'New match',exact:true}).click();
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await expect(page.getByText('Petr WINS')).toBeVisible();
});
