import { test, expect } from '@playwright/test';
test('Russian locale, synchronized language, sound toggles, Space and Backspace persist', async ({page,context}) => {
  await page.addInitScript(() => {
    (window as unknown as {soundStarts:number}).soundStarts=0;
    const original=AudioBufferSourceNode.prototype.start;
    AudioBufferSourceNode.prototype.start=function(...args: Parameters<typeof original>) {
      (window as unknown as {soundStarts:number}).soundStarts++;
      return original.apply(this,args);
    };
  });
  const starts = () => page.evaluate(() => (window as unknown as {soundStarts:number}).soundStarts);
  await page.goto('/');
  await expect(page.locator('html')).toHaveAttribute('lang','ru');
  await page.getByLabel('Спортсмен A',{exact:true}).fill('Иван');
  await page.getByLabel('Спортсмен B',{exact:true}).fill('Пётр');
  await page.getByRole('button',{name:'СОЗДАТЬ СХВАТКУ'}).click();
  await page.getByLabel('A: плюс 2',{exact:true}).click();
  const popup = context.waitForEvent('page');
  await page.getByRole('button',{name:'Открыть зрительское табло'}).click();
  const display=await popup;
  await expect(display.locator('html')).toHaveAttribute('lang','ru');
  await page.keyboard.press('Space');
  await expect.poll(starts).toBe(1);
  await page.keyboard.press('Space');
  await expect(page.getByRole('button',{name:'ПРОДОЛЖИТЬ'})).toBeVisible();
  await page.keyboard.press('Space');
  await expect.poll(starts).toBe(1);
  await page.keyboard.press('Backspace');
  await expect(page.getByRole('heading',{name:'Сбросить таймер схватки?'})).toBeVisible();
  await page.getByRole('button',{name:'Подтвердить',exact:true}).click();
  await expect(page.getByLabel('Изменить оставшееся время')).toHaveText('05:00');
  await page.getByLabel('Настройки',{exact:true}).click();
  await page.getByLabel('Звук при первом запуске таймера').uncheck();
  await page.getByLabel('Звук по окончании времени').uncheck();
  await page.getByLabel('Язык',{exact:true}).selectOption('en');
  await expect(display.locator('html')).toHaveAttribute('lang','en');
  await page.getByLabel('Language',{exact:true}).selectOption('ru');
  await page.screenshot({path:'test-results/settings-ru.png'});
  await page.getByLabel('Закрыть диалог').click();
  await page.getByLabel('Изменить оставшееся время').click();
  await page.getByRole('textbox',{name:'Оставшееся время'}).fill('00:01');
  await page.getByRole('button',{name:'Подтвердить изменение'}).click();
  await page.keyboard.press('Space');
  await expect(display.getByText('ВРЕМЯ ИСТЕКЛО',{exact:true})).toBeVisible();
  await expect.poll(starts).toBe(1);
  await page.getByRole('dialog').locator('.dialog-actions button').first().click();
  await page.getByLabel('Настройки',{exact:true}).click();
  await page.getByLabel('Звук по окончании времени').check();
  await page.getByLabel('Закрыть диалог').click();
  await page.getByLabel('Изменить оставшееся время').click();
  await page.getByRole('textbox',{name:'Оставшееся время'}).fill('00:01');
  await page.getByRole('button',{name:'Подтвердить изменение'}).click();
  await page.keyboard.press('Space');
  await expect(display.getByText('ВРЕМЯ ИСТЕКЛО',{exact:true})).toBeVisible();
  await expect.poll(starts,{timeout:10000}).toBe(2);
  await page.screenshot({path:'test-results/control-ru.png'});
  await expect(page.locator('body')).toHaveJSProperty('scrollHeight',768);
  await page.reload();
  await page.getByRole('button',{name:'ВОССТАНОВИТЬ СХВАТКУ'}).click();
  await page.getByLabel('Настройки',{exact:true}).click();
  await expect(page.getByLabel('Звук при первом запуске таймера')).not.toBeChecked();
  await expect(page.getByLabel('Звук по окончании времени')).toBeChecked();
  await expect(page.getByLabel('Язык',{exact:true})).toHaveValue('ru');
});
