import { useState } from 'react';
import { bjjActions, grapplingActions, categories, categoryLabels, type Rules, type Sport, type ScoringAction } from '../domain/rules';
import { useTranslation } from '../app/i18n';
import { Modal } from './Modal';
function savedActions():ScoringAction[]{try{const value=JSON.parse(localStorage.getItem('tatami.custom-rules.v1')||'[]');return Array.isArray(value)?value.filter(a=>typeof a?.label==='string'&&a.label.trim()&&Number.isInteger(a.points)&&a.points>0&&a.points<=99).slice(0,30):[];}catch{return [];}}
export function RulesPicker({rules,onChange,compact=false}:{rules:Rules;onChange?:(r:Rules)=>void;compact?:boolean}) {
  const {t}=useTranslation();
  const [saved,setSaved]=useState(savedActions);
  const [editor,setEditor]=useState(false),[guide,setGuide]=useState(false);
  const [actions,setActions]=useState<ScoringAction[]>([]),[label,setLabel]=useState(''),[points,setPoints]=useState('2'),[error,setError]=useState('');
  const openEditor=()=>{let list=rules.sport==='custom'?rules.actions:[];try {if(!list.length) {const saved=JSON.parse(localStorage.getItem('tatami.custom-rules.v1')||'[]'); if(Array.isArray(saved)) list=saved.filter(a=>typeof a?.label==='string'&&a.label.trim()&&Number.isInteger(a.points)&&a.points>0&&a.points<=99);}}catch{/* Ignore invalid saved data. */}setActions(list);setEditor(true);};
  const select=(sport:Sport)=> {if(sport==='custom') {openEditor();return;}onChange?.({sport,category:sport==='bjj'?'adult':'senior',belt:'white',actions:sport==='bjj'?bjjActions:grapplingActions});};
  return <div className={`rules-picker ${compact?'compact':''}`}>
    <div className="sport-options" role="group" aria-label={t('Sport')}>
      {(['bjj','grappling','custom'] as const).map(sport=><label key={sport}><input type="checkbox" checked={rules.sport===sport} disabled={!onChange} onChange={()=>select(sport)}/>{t(sport==='bjj'?'BJJ · IBJJF':sport==='grappling'?'Grappling · UWW':'Add custom rules')}</label>)}
      <button type="button" onClick={()=>setGuide(true)}>{t('Rules guide')}</button>
    </div>
    {saved.length>0&&<div className="saved-rules"><button type="button" disabled={!onChange} onClick={openEditor}>{t('My saved rules')} · {saved.length}</button><small>{t('Saved on this computer and available for future matches.')}</small></div>}
    {compact?<small>{t(categoryLabels[rules.category])}{rules.sport==='bjj'&&!rules.category.startsWith('kids')?` · ${t(rules.belt+' belt')}`:''}</small>:<div className="category-options"><label>{t('Age category')}<select aria-label={t('Age category')} disabled={!onChange} value={rules.category} onChange={e=>onChange?.({...rules,category:e.target.value,belt:'white'})}>{categories[rules.sport].map(c=><option key={c} value={c}>{t(categoryLabels[c])}</option>)}</select></label>{rules.sport==='bjj'&&!rules.category.startsWith('kids')&&<label>{t('Belt')}<select aria-label={t('Belt')} disabled={!onChange} value={rules.belt} onChange={e=>onChange?.({...rules,belt:e.target.value})}>{(rules.category==='juvenile'?['white','blue','purple']:['white','blue','purple','brown','black']).map(b=><option key={b} value={b}>{t(b+' belt')}</option>)}</select></label>}</div>}
    {editor&&<Modal title="Custom scoring rules" close={()=>setEditor(false)}><p>{t('Custom rules summary')}</p><form className="action-editor" onSubmit={e=>{e.preventDefault();const n=Number(points);if(label.trim()&&Number.isInteger(n)&&n>0&&n<=99&&!actions.some(a=>a.label.toLowerCase()===label.trim().toLowerCase())){setActions([...actions,{label:label.trim(),points:n}]);setLabel('');}}}><label>{t('Action')}<input required maxLength={60} value={label} onChange={e=>setLabel(e.target.value)} placeholder={t('Action name')}/></label><label>{t('Point value')}<input required type="number" min="1" max="99" step="1" value={points} onChange={e=>setPoints(e.target.value)}/></label><button className="primary" disabled={actions.length>=30||!label.trim()||actions.some(a=>a.label.toLowerCase()===label.trim().toLowerCase())}>{t('Add action')}</button></form><div className="custom-actions">{actions.map((a,i)=><div key={i}><span>{a.label}</span><strong>+{a.points}</strong><button aria-label={`${t('Delete')} ${a.label}`} onClick={()=>setActions(actions.filter((_,index)=>index!==i))}>×</button></div>)}</div>{error&&<p role="alert">{t(error)}</p>}<div className="dialog-actions"><button onClick={()=>setEditor(false)}>{t('Cancel')}</button><button className="primary" disabled={!actions.length} onClick={()=>{try{localStorage.setItem('tatami.custom-rules.v1',JSON.stringify(actions));setSaved(actions);onChange?.({sport:'custom',category:'custom',belt:'white',actions});setEditor(false);}catch{setError('Local save failed. Keep this window open until storage is available.');}}}>{t('Save rules')}</button></div></Modal>}
    {guide&&<Modal title="Rules guide" close={()=>setGuide(false)}><div className="rules-guide"><h3>IBJJF · v6.1 · 06/2024</h3><p>{t('IBJJF summary')}</p><p>{t('IBJJF age restrictions')}</p><p>{t('IBJJF penalties summary')}</p><h3>UWW Grappling · 05/2025</h3><p>{t('UWW summary')}</p><p>{t('UWW overtime summary')}</p><h3>{t('Sources')}</h3><p>{t('Referees judge legal techniques and position control. Consult the complete rulebook for the selected division.')}</p><a href="https://ibjjf.com/books-videos" target="_blank" rel="noreferrer">IBJJF — Books & Videos</a><a href="https://cdn.uww.org/2025-05/grappling_rules_2025.pdf" target="_blank" rel="noreferrer">UWW — Grappling Rules, May 2025</a><small>{t('Rules checked')}: 13.09.2026</small></div></Modal>}
  </div>;
}
